{"name": "Неуспешная аутентификация под несуществующими данными", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 404 and {'code': 404,...ь не найдена'} == {'message': '...ь не найдена'}\n +  where 404 = <Response [404]>.status_code\n  \n  Omitting 1 identical items, use -vv to show\n  Left contains 1 more item:\n  {'code': 404}\n  Use -v to get more diff)", "trace": "self = <tests.test_login_courier.TestLoginCourier object at 0x000001D41CD47080>\n\n    @allure.title('Неуспешная аутентификация под несуществующими данными')\n    def test_courier_login_with_invalid_data(self):\n        random_payload = {'login': generate_login(), 'password': generate_password()}\n        response = requests.post(Urls.url_login_courier, data=random_payload)\n>       assert response.status_code == 404 and response.json() == {\"message\": \"Учетная запись не найдена\"}\nE       AssertionError: assert (404 == 404 and {'code': 404,...ь не найдена'} == {'message': '...ь не найдена'}\nE        +  where 404 = <Response [404]>.status_code\nE         \nE         Omitting 1 identical items, use -vv to show\nE         Left contains 1 more item:\nE         {'code': 404}\nE         Use -v to get more diff)\n\ntests\\test_login_courier.py:30: AssertionError"}, "start": 1719739886432, "stop": 1719739886479, "uuid": "1caacb76-2e10-4732-913a-c4cb4ce2b74b", "historyId": "43c78cbc880d86d673bc980eb8a4cded", "testCaseId": "43c78cbc880d86d673bc980eb8a4cded", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_login_with_invalid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "PC-MASTER"}, {"name": "thread", "value": "12584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}